# Generated by Django 5.1.1 on 2024-12-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chindi', models.TextField()),
                ('cenglish', models.TextField()),
            ],
        ),
    ]
